### ISSUE TITLE
Support for Mongoose Populate 

### ISSUE THREAD

**Issue by anoopsinghbayes** [nodkz/graphql-compose-mongoose#28]
Mongoose provides a way to define relationships between schema,
I was wondering why do we have to define relationships separately as we can iterate over the mongoose model to find out 'ref' fields from the schema definition and build up the populate query as you do for projection fields

**Comment by nodkz** [comment]
Cause this brings more evil than helps:
- You should have explicit TypeComposers for related models, to have ability extend and modify it. Otherwise it would be tricky to modify nested types.
- Mutations with nesting also introduce many questions (restrictions, error handling).

I think that related models in mongoose is not the same what usually exposed as public API.

**Comment by yoadsn** [comment]
@nodkz I totally agree - both of us came from mongoose-graffiti experience and know how bad the control was when the inferred the resolution of relations from the mongoose "ref" property.
Another point, is that the "populate" method from mongoose could be optimized in terms of access plan if you know your data model. (For example batching access, using data-loader, pre-aggregating stuff with a "lookup", accessing a cache layer).
Explicitly defining the relationship resolver bring this control back.

**Comment by anoopsinghbayes** [comment]
:thumbsup:

**Comment by nodkz** [comment]
@yoadsn great answer! Thanks!
