### ISSUE TITLE
Allow integer _ids to work with findByIds?

### ISSUE THREAD

**Issue by unkleho** [nodkz/graphql-compose-mongoose#4]
Hi there. First up, nice work with this library - my team has been experimenting with it for our Graphql project and it has saved a lot of time.

We have just run into an issue with our primary key (_id) in some of our models. We are using an integer/number for _id rather than a MongoId. While this works with `Model.getResolver('findById')`, it doesn't work with `Model.getResolver('findByIds)`.

I actually get a cast error when doing relations:
```GQC ERROR: relation for Model.parents throws error:
{ [CastError: Cast to number failed for value "00016cb0dd2f1e4b7df8d7bd" at path "_id"]
  message: 'Cast to number failed for value "00016cb0dd2f1e4b7df8d7bd" at path "_id"',
  name: 'CastError',
  kind: 'number',
  value: 00016cb0dd2f1e4b7df8d7bd,
  path: '_id',
  reason: undefined }
```

I've pinpointed the issue here:
[https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/resolvers/findByIds.js#L59-L60](https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/resolvers/findByIds.js#L59-L60)

It looks like there is a MongoId check on the id, and then it converts to a MongoId before being put into the selector query.

Is there a particular reason for this? Some flexibilty would be great - to my knowledge, Mongoose and Mongo have no issues with _id being an integer. Integers also work with findById so we assumed it would also work with findByIds.

Happy to submit a pull request, just wanted to check first :)

Many thanks
unkleho

**Comment by nodkz** [comment]
I'm glad to hear such words. Mostly that somebody wants to make PR.

I do not remember why I add this checks. But definitely, `findByIds` should accept integers. So feel free to make PR. 

Also will be nice if you add tests for [findById](https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/resolvers/__tests__/findById-test.js) and [findByIds](https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/resolvers/__tests__/findByIds-test.js) that they accept integer ids. I would not want it to break down in the future.

`npm run test` - run tests one-time
`npm run watch` - automatically run tests after any file changes

**Comment by unkleho** [comment]
Hi nodkz,

I've tried to get this project up and running but running into some issues. This is actually my first time contributing so please excuse my ignorance. If I could get some help that would be great.

These are the steps i've taken: 
1. Cloned graphql-compose-mongoose in new folder
2. Installed dependencies, also installed peer dependencies (graphql, graphql-compose, graphql-compose-connection, mongoose)
3. Ran `npm link`, then `npm run build` and lastly `npm link graphql-compose-mongoose` in my own project folder.
4. Started my project and got this error:
```
Error: You should provide TypeComposer instance to composeWithRelay method
    at composeWithRelay (/my-project/node_modules/graphql-compose-relay/lib/composeWithRelay.js:37:11)
    at Object.<anonymous> (/my-project/build/schema/User.js:25:65)
```

It is all okay when I unlink - have I missed something with the build process?

Thanks
Unkle

**Comment by nodkz** [comment]
Wow, now I understood, how is complicated to start to contribute to graphql-compose plugins with peer dependencies and **connect it with your app**. 

So the problem is that modules may use TypeComposer from different places. And instance of TypeCompose from one folder will not be `instanceOf` TypeComposer from another folder. So to resolve this problem needs to make one source of true for code via linking all peer packages.

So if you want to alive `graphql-compose` packages with your app you need:

### 1. Clone all 6 peer-depended packages from github and build them. 
Open terminal and choose folder where will be created `npm-forks` folder with all packages. Copy all lines and wait about 10 minutes.
```
mkdir npm-forks
cd npm-forks

git clone https://github.com/graphql/graphql-js.git
cd graphql-js
npm install
npm run build
cd dist
npm link
cd ../..

git clone https://github.com/Automattic/mongoose.git
cd mongoose
npm link
cd ..

git clone https://github.com/nodkz/graphql-compose.git
cd graphql-compose
npm install
npm run build
npm run link
cd ..

git clone https://github.com/nodkz/graphql-compose-connection.git
cd graphql-compose-connection
npm install
npm run build
npm run link
cd ..

git clone https://github.com/nodkz/graphql-compose-relay.git
cd graphql-compose-relay
npm install
npm run build
npm run link
cd ..

git clone https://github.com/nodkz/graphql-compose-mongoose.git
cd graphql-compose-mongoose
npm install
npm run build
npm run link
cd ..

echo "Congrat! It's done!"
```

### 2. Add scripts for fast linking/unlinking packages to your package.json:
```js
  "scripts": {
    ...
    "link": "npm link graphql graphql-compose graphql-compose-connection graphql-compose-mongoose graphql-compose-relay mongoose",
    "unlink": "npm unlink graphql graphql-compose graphql-compose-connection graphql-compose-mongoose graphql-compose-relay mongoose && npm i"
}
```
And run `npm run link` in your app to link packages. When you are done, just run `npm run unlink` ti return back all packages from npmjs.

### 3. How to make changes in libs.
Change something in `graphql-compose-mongoose`.
Run `npm run build`, after that you need to restart your server app. It should get fresh build lib's files (cause `your_app/node_modules/graphql-compose-mongoose` is symlinked with `npm-forks/graphql-compose-mongoose`. 

Say it again, you should not forget to run `npm run build` before restarting your app. Otherwise, your app will see old files.

### 4. How to send PR
Somehow I described it here https://medium.com/@nodkz/how-to-fix-nodejs-packages-within-your-app-and-send-pull-request-with-your-changes-8b4dcb89492b#.7zpm09l16
After reading this article you may want to add your forked repo to `remote`s (https://help.github.com/articles/adding-a-remote/).
```
# add `fork` remote to your forked version of repository on github (run only once)
git remote add fork https://github.com/unkleho/graphql-compose-mongoose.git

# load all last commits from my repo (do it before every time when want to create new branch)
git fetch origin 
# update files on your disk
git checkout master

# create new branch which will be connected to your fork version
git checkout -b patch-1 fork/patch-1

# change code, add all files to commit and make the commit
git add . 
git commit -m 'Some commit message'

# push your data to your fork repo on github
git push fork
```


---
PS. I think you are brave and complete this achievement. 😅 
In the same way, you may fix not only my packages! Any packages that uses your app.

PSS. Right now I do not link my `graphql-compose` packages with my project. I write tests and check code only with them.

**Comment by unkleho** [comment]
Hi sorry about the late reply. I'll try and tackle this next week. Thanks for the instructions, the Medium article is perfect.
