### ISSUE TITLE
GraphQL 0.11 : Can only create NonNull of a Nullable GraphQLType but got: MongoID

### ISSUE THREAD

**Issue by toverux** [nodkz/graphql-compose-mongoose#57]
One of the drawbacks of pre-v1 software is instability and GraphQL does not escapes that rule :smile: 

Starting from GraphQL v.0.11.0 and later, the app crashes when building the schema. Relavant stack trace:

```
/home/morgan/.../node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
          ^
Error: Can only create NonNull of a Nullable GraphQLType but got: MongoID.
    at invariant (/home/morgan/.../node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLNonNull (/home/morgan/.../node_modules/graphql/type/definition.js:780:84)
```

I assume that a breaking change in GQL breaks graphql-compose-mongoose.

_(Workaround: downgrade to graphql@0.10.5)_

**Comment by nodkz** [comment]
In my app all works perfectly with `graphql@0.11.2`.

It looks like that you have different `graphql` versions in your `node_modules`. Try to update all packages that use graphql (eg `graphql-express`, `react-relay`) and reinstall all packages from scratch. If it does not help, try to remove `graphql` folders in `graphql-compose/node_modules/graphql`, `graphql-express/node_modules/graphql`, `maybe_any_other_pkg/node_modules/graphql`. All packages that use `graphql` should use the same `graphql` package, because they all use checks via `instanceof` (that's why `graphql-compose` has `graphql` as peer-dependency for reducing package versions hell between different libs).

**Comment by toverux** [comment]
Well, you were right, I've upgraded graphql again, then deleted node_modules and reinstalled everything from the lockfile, and that works. Using yarn, I'm not used to that type of problems anymore...
Sorry sorry :)
